---
- hosts: localhost
  connection: local

  vars:
    # Connection vars 
    u_token: YOUR_API_TOKEN
    u_ssh: YOUR_SSH
    # Droplets vars
    droplets:
      - { name: a4d.lamp.varnish, group: "lamp_varnish" }
      - { name: a4d.lamp.www.1, group: "lamp_www" }
      - { name: a4d.lamp.www.2, group: "lamp_www" }
      - { name: a4d.lamp.db.1, group: "lamp_db" }
      - { name: a4d.lamp.db.2, group: "lamp_db" }
      - { name: a4d.lamp.memcached, group: "lamp_memcached" }

  tasks:
    - name: Provision DigitalOcean droplets.
      community.digitalocean.digital_ocean_droplet:
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        oauth_token: "{{ u_token }}"
        private_networking: true
        size: "{{ item.size | default('s-1vcpu-512mb-10gb') }}"
        image: "{{ item.image | default('centos-7-x64') }}"
        region: "{{ item.region | default('fra1') }}"
        # Customize this default for your account.
        ssh_keys:
          - "{{ u_ssh }}"
        unique_name: true
      register: created_droplets
      with_items: "{{ droplets }}"
      
    - name: Run generate_hosts.py
      ansible.builtin.command: python3 YOUR_PATH/generate_hosts.py
